language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y apache2-prefork-dev
- sudo apt-get install -y zip
script: make all
before_deploy: ./.travis.beforeDeploy.sh
deploy:
  provider: releases
  api_key:
    secure: sdliy7ckcG3LJo4Zjg1Bjavh6sKR646w/FlYrS84RJSaTr7uDWZt7Bh5tZktECxzWwuKkRDCguA1Q7Klx8O/1M6PtqdV+Ffgnen2WlMtmNF0iKFeVn13igNxn6khClGatUXlGNRpEMtbu3BRa4mJOzQ6LT5xB15/UEzQnGOTSW0=
  file: "./src/.libs/mod_less.so"
  skip_cleanup: true
  on:
    tags: true
    repo: Personalwerk/libapache2-mod-less_beta1
after_deploy: ./.travis.afterDeploy.sh
